auto:	          true

markdown:         rdiscount
pygments:         true
paginate:         6
permalink:        /:title

title:            LiWei
url:              fisherlee.github.com
#feed:             /atom.xml
author:
    name:         Li Wei
   #twitter:      twitter.com/beiyuu
description:      "LiWei Blog"
author_info:      <a href="fisherlee.github.com">LiWei</a>

copyright:
    - Design by  LiWei  &copy; 2013
